#!/usr/local/bin/perl -w
#
# $Revision: 1.3 $
#
# $Date: 1998/12/01 02:56:34 $

use XML::Parser;

my $file = shift;

die "Can't find file \"$file\""
  unless -f $file;
    
my $count = 0;

my $parser = new XML::Parser(ErrorContext => 2);

$parser->setHandlers(Comment => \&comments);

$parser->parsefile($file);

print "Found $count comments.\n";

################
## End of main
################

sub comments
{
    my ($p, $data) = @_;

    my $line = $p->current_line;
    $data =~ s/\n/\n\t/g;
    print "$line:\t<!--$data-->\n";
    $count++;

}  # End comments

# Tell Emacs that this is really a perl script
# Local Variables:
# mode:perl
# End:
